### ISSUE TITLE
Download-link not working via IPv6

### ISSUE THREAD

**Issue by lyxys** [libssh2/www#17] opened 2022-01-11 15:34 UTC
www.libssh2.org publishes a download link for the source package, at the time of writing it is
https://www.libssh2.org/download/libssh2-1.10.0.tar.gz
DNS has an IPv6-address for www.libssh2.org (2a02:750:7:3305::2aa) but the server does not answer on https via IPv6. Because of this DNS-entry, clients on IPv6-only nets can not automatically fall back to a NAT64 connection. So please get the download server working on IPv6, or if this is not possible, remove the IPv6 DNS entry.
Thanks

**Comment by vszakats** [comment] 2023-05-03 22:47
Cannot confirm this at the time of writing this. The name isn't resolved to IPv6 in local tests. Qualys SSL Labs also doesn't detect IPv6: https://www.ssllabs.com/ssltest/analyze.html?d=www.libssh2.org&hideResults=on&latest

Closing this for now, please reopen if still an issue.

**Closed by vszakats** 2023-05-03 22:47 UTC

**Comment by dfandrich** [comment] 2023-05-03 23:07
This was a dupe of libssh2/libssh2#775

**Comment by vszakats** [comment] 2023-05-03 23:10
Neat, thanks, so we fixed this a few months ago. 👍
